import * as React from "react";
import {
  AlertCircle,
  AlertTriangle,
  Image as ImageIcon,
  Info,
  Loader2,
  RefreshCcw,
  Sparkles,
} from "lucide-react";
import type { FarmCaptionSeverity, FarmImageCaption } from "@/types";
import { useAnalysis } from "@/state/analysis";
import { cn } from "@/lib/utils";

const SEVERITY_STYLE: Record<
  FarmCaptionSeverity,
  { ring: string; bg: string; text: string; iconColor: string; Icon: typeof Info }
> = {
  info: {
    ring: "ring-sky-200",
    bg: "bg-sky-50",
    text: "text-sky-900",
    iconColor: "text-sky-600",
    Icon: Info,
  },
  warning: {
    ring: "ring-amber-200",
    bg: "bg-amber-50",
    text: "text-amber-900",
    iconColor: "text-amber-600",
    Icon: AlertTriangle,
  },
  critical: {
    ring: "ring-rose-200",
    bg: "bg-rose-50",
    text: "text-rose-900",
    iconColor: "text-rose-600",
    Icon: AlertCircle,
  },
};

function CaptionRow({ caption }: { caption: FarmImageCaption }) {
  const s = SEVERITY_STYLE[caption.severity];
  const { Icon } = s;
  return (
    <div
      className={cn(
        "flex items-start gap-2 rounded-xl px-3 py-2 ring-1",
        s.bg,
        s.ring
      )}
    >
      <Icon className={cn("mt-0.5 h-4 w-4 flex-none", s.iconColor)} />
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <span
            className={cn(
              "rounded-full bg-white px-1.5 py-0.5 text-[10px] font-semibold tracking-wide ring-1",
              s.ring,
              s.text
            )}
          >
            {caption.row + 1}·{caption.col + 1}
          </span>
          <span className={cn("text-sm font-medium", s.text)}>
            {caption.text}
          </span>
        </div>
      </div>
    </div>
  );
}

interface Props {
  className?: string;
}

export function FarmImageView({ className }: Props) {
  const {
    current,
    farmImage,
    farmImageLoading,
    farmImageError,
    loadFarmImage,
  } = useAnalysis();

  const hasField = Boolean(current?.geometry?.coordinates?.[0]);
  const onGenerate = () => {
    if (!current) return;
    void loadFarmImage(current.geometry);
  };

  const captions = React.useMemo(() => {
    if (!farmImage) return [] as FarmImageCaption[];
    const order = { critical: 0, warning: 1, info: 2 } as const;
    return [...farmImage.captions].sort(
      (a, b) =>
        order[a.severity] - order[b.severity] ||
        a.row - b.row ||
        a.col - b.col
    );
  }, [farmImage]);

  return (
    <div
      className={cn(
        "rounded-2xl bg-gradient-to-b from-sky-50 via-white to-emerald-50/50 p-5 ring-1 ring-slate-200/80 shadow-soft",
        className
      )}
    >
      <div className="mb-3 flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-lg font-semibold text-slate-900">
            Your field — annotated overview
          </h2>
          <p className="mt-0.5 text-sm text-slate-500">
            {farmImage?.overallSummary ||
              "An AI-generated top-down view of your field, with arrows pointing at the spots that need attention."}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {farmImageLoading && (
            <span className="inline-flex items-center gap-1.5 rounded-full bg-white px-3 py-1 text-xs font-medium text-slate-600 ring-1 ring-slate-200">
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
              Generating image…
            </span>
          )}
          {farmImage && !farmImageLoading && (
            <button
              type="button"
              onClick={onGenerate}
              className="inline-flex items-center gap-1.5 rounded-full bg-white px-3 py-1 text-xs font-medium text-slate-700 ring-1 ring-slate-200 hover:bg-slate-50"
            >
              <RefreshCcw className="h-3.5 w-3.5" />
              Regenerate
            </button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-[minmax(0,1fr)_300px]">
        <div className="relative flex min-h-[280px] items-center justify-center overflow-hidden rounded-xl bg-white ring-1 ring-emerald-100">
          {farmImage ? (
            <img
              src={`data:${farmImage.mimeType};base64,${farmImage.imageBase64}`}
              alt="Annotated farm overview generated by AI"
              className="block h-auto w-full max-w-full object-contain"
            />
          ) : (
            <EmptyState
              hasField={hasField}
              loading={farmImageLoading}
              error={farmImageError}
              onGenerate={onGenerate}
            />
          )}

          {farmImageLoading && farmImage && (
            <div className="pointer-events-none absolute inset-0 bg-white/40" />
          )}
        </div>

        <div className="flex flex-col gap-2">
          <div className="rounded-xl bg-white p-3 ring-1 ring-slate-200">
            <p className="text-xs font-semibold uppercase tracking-wider text-slate-500">
              Action items
            </p>
            <p className="mt-1 text-xs text-slate-500">
              Each badge (e.g.&nbsp;
              <span className="rounded bg-slate-100 px-1 font-mono text-[10px]">
                2·3
              </span>
              ) matches the labelled cell in the field-boundary mini-map above.
            </p>
          </div>

          {captions.length === 0 && farmImage && (
            <div className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800 ring-1 ring-emerald-200">
              No problem zones detected — the field looks healthy.
            </div>
          )}
          {captions.map((c) => (
            <CaptionRow key={`${c.row}-${c.col}`} caption={c} />
          ))}
          {!farmImage && !farmImageLoading && (
            <div className="rounded-xl bg-white p-3 text-xs text-slate-500 ring-1 ring-slate-200">
              Action items will appear here once the overview is generated.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function EmptyState({
  hasField,
  loading,
  error,
  onGenerate,
}: {
  hasField: boolean;
  loading: boolean;
  error: string | null;
  onGenerate: () => void;
}) {
  if (loading) {
    return (
      <div className="flex flex-col items-center gap-2 px-6 py-12 text-center text-slate-500">
        <Loader2 className="h-8 w-8 animate-spin text-padi-600" />
        <p className="text-sm font-medium text-slate-700">
          Asking AI to draw your annotated overview…
        </p>
        <p className="text-xs">This usually takes 10–20 seconds.</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center gap-3 px-6 py-12 text-center">
        <AlertCircle className="h-8 w-8 text-rose-600" />
        <p className="max-w-md text-sm font-medium text-rose-800">{error}</p>
        <button
          type="button"
          onClick={onGenerate}
          disabled={!hasField}
          className="inline-flex items-center gap-1.5 rounded-full bg-padi-600 px-3 py-1 text-xs font-medium text-white shadow-sm hover:bg-padi-700 disabled:opacity-60"
        >
          <RefreshCcw className="h-3.5 w-3.5" />
          Try again
        </button>
      </div>
    );
  }

  if (!hasField) {
    return (
      <div className="flex flex-col items-center gap-2 px-6 py-12 text-center text-slate-500">
        <ImageIcon className="h-8 w-8 text-slate-400" />
        <p className="text-sm font-medium text-slate-700">
          Draw a field first
        </p>
        <p className="max-w-sm text-xs">
          Once you've drawn a polygon and run an analysis, you can generate an
          annotated overview image here.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center gap-3 px-6 py-12 text-center">
      <Sparkles className="h-8 w-8 text-padi-600" />
      <p className="text-sm font-medium text-slate-800">
        Generate the annotated farm overview
      </p>
      <p className="max-w-sm text-xs text-slate-500">
        AI will combine your satellite imagery and zone analysis into a single
        labelled top-down picture so you know exactly where to act.
      </p>
      <button
        type="button"
        onClick={onGenerate}
        className="inline-flex items-center gap-1.5 rounded-full bg-padi-600 px-4 py-1.5 text-sm font-medium text-white shadow-sm hover:bg-padi-700"
      >
        <Sparkles className="h-4 w-4" />
        Generate overview image
      </button>
    </div>
  );
}
